export { runAfk } from "./main.js";
export { runGhAfk } from "./gh-main.js";
export { runChief } from "./chief-main.js";
export {
  runChiefLoop,
  type ChiefLoopConfig,
  type ChiefLoopOptions,
  type ExternalChiefBridge,
  type ExternalChiefBridgeContext,
  type ChiefRunResult,
  type ChiefRunState,
  type ChiefRunStatus,
} from "./chief-loop.js";
export {
  parseChiefDecision,
  parseExternalChiefVerdict,
  type ChiefDecision,
  type ChiefVerdict,
  type ExternalChiefVerdict,
} from "./chief.js";
export {
  defaultChiefConfig,
  loadChiefConfig,
  type ChiefConfig,
  type ChiefAgentConfig,
  type ChiefGuiBridgeConfig,
  type ChiefMode,
} from "./chief-config.js";
export {
  runMachineGate,
  type MachineGateOptions,
  type MachineGateResult,
  type GateCommandResult,
} from "./machine-gate.js";
export {
  GitGuard,
  isControllerOwnedPath,
  workspaceFingerprint,
  type AcceptanceControls,
  type RepoSnapshot,
  type WorkspaceFingerprint,
  type GuardViolation,
} from "./git-guard.js";
export type {
  AgentName,
  AgentSelection,
  AgentSelectionSource,
  StageMeta,
} from "./agents/index.js";
export { runLoop, type LoopOptions } from "./loop.js";
export { STAGES, type Stage } from "./stages.js";
export {
  renderTemplate,
  type RenderOptions,
  type RenderVars,
} from "./render.js";
export { ensureImage, runStage } from "./runner.js";
export {
  RUN_STATE_VERSION,
  PROJECT_STATE_VERSION,
  V3_PHASES,
  parseRunState,
  parseProjectState,
  hydrateRunState,
  hydrateProjectState,
  loadRunState,
  loadProjectState,
  saveRunState,
  saveProjectState,
  type RunState,
  type ProjectState,
  type ProjectTask,
  type V3Phase,
  type WaitingHandoff,
  type SelectWaitingHandoff,
  type ReviewWaitingHandoff,
  type FutureWaitingHandoff,
} from "./v3/state.js";
export { assertRunState, assertProjectState } from "./v3/state-invariants.js";
export {
  writeJsonAtomic,
  writeTextAtomic,
  writeJsonImmutable,
  writeTextImmutable,
} from "./v3/atomic-json.js";
export {
  PHASE_REGISTRY,
  phaseDefinition,
  isRunnablePhase,
  dispatchPhase,
  type PhaseDefinition,
  type PhaseHandler,
} from "./v3/phases.js";
export {
  ROUND_ARTIFACTS,
  getChiefRunDir,
  roundName,
  getRoundDir,
  getRoundArtifactPath,
  type RoundArtifact,
} from "./v3/rounds.js";
export {
  ActiveWriterLockError,
  activeWriterLockPath,
  inspectActiveWriterLock,
  acquireActiveWriterLock,
  refreshActiveWriterLock,
  releaseActiveWriterLock,
  clearStaleActiveWriterLock,
  type ActiveWriterLock,
  type LockInspection,
  type LockKind,
} from "./v3/lock.js";
export {
  PROJECT_STATE_RELATIVE_PATH,
  PROJECT_PLAN_RELATIVE_PATH,
  projectStatePath,
  projectPlanPath,
  canonicalizeValue,
  canonicalizeProjectState,
  hashProjectState,
  getReadyTasks,
  renderProjectPlan,
  loadProjectStateFromProject,
  saveProjectStateToProject,
} from "./v3/project-plan.js";
export {
  SELECT_HANDOFF_KIND,
  parseChiefSelectDecision,
  validateChiefSelectDecision,
  prepareSelectHandoff,
  applySelectDecision,
  type SelectAction,
  type ReferenceDecision,
  type ReferenceCheck,
  type ChiefSelectDecision,
  type SelectHandoff,
  type SelectPreparation,
} from "./v3/select.js";
export {
  REVIEW_HANDOFF_KIND,
  REVIEW_OPEN_MARKER,
  REVIEW_CLOSE_MARKER,
  parseChiefReviewDecision,
  validateChiefReviewDecision,
  prepareReviewHandoff,
  applyReviewDecision,
  verifyReviewCheckpoint,
  type ChiefReviewDecision,
  type ReviewHandoff,
  type ReviewStage,
  type ReviewPreparation,
  type ReviewRemoteUrlResolver,
} from "./v3/review.js";
export {
  buildWorkerPrompt,
  runWorkerPhase,
  resumeTechnicalBlockedWorker,
  type V3WorkerConfig,
  type V3WorkerRunner,
  type WorkerPhaseResult,
} from "./v3/worker.js";
export {
  finiteWorkerArgs,
  runFiniteCodexWorker,
  type FiniteWorkerOptions,
} from "./v3/finite-worker.js";
export {
  GOAL_STATUSES,
  NativeCodexGoalTransport,
  pauseGoalForShutdown,
  runNativeGoalWorker,
  type GoalStatus,
  type GoalRecord,
  type GoalTransport,
  type GoalWaitResult,
  type GoalWaitOptions,
  type GoalObservation,
  type GoalWorkerArtifact,
  type GoalLivenessArtifact,
  type GoalStallArtifact,
  type GoalWorkerResult,
} from "./v3/goal-worker.js";
export {
  runMachineGatePhase,
  type V3GateConfig,
  type MachineGatePhaseResult,
} from "./v3/machine-gate.js";
export {
  MissingRequiredGateEvidenceError,
  assertCheckpointGateEvidence,
  evaluateRequiredGateEvidence,
  normalizeRequiredCommands,
  requiredGateFailureSummary,
  type GateEvidenceFailure,
  type GateEvidenceFailureCode,
  type RequiredGateVerdict,
} from "./v3/gate-evidence.js";
export {
  runCheckpointPhase,
  type V3CheckpointConfig,
  type CheckpointResult,
} from "./v3/checkpoint.js";
export {
  runV3WorkSlice,
  type V3WorkConfig,
  type V3WorkResult,
} from "./v3/work.js";
export {
  CONTROLLED_STOP_REASONS,
  evaluateSupervisorDisposition,
  supervisorFailureFingerprint,
  supervisorRestartBackoffMs,
  type SupervisorDisposition,
  type SupervisorDispositionKind,
  type SupervisorEvaluationInput,
  type SupervisorRunSnapshot,
} from "./v3/supervisor-policy.js";
export {
  BACKEND_FAILURE_CLASSES,
  BACKEND_STOP_EVIDENCE_FILENAME,
  BACKEND_STOP_REASONS,
  EXECUTION_BACKEND_KINDS,
  EXECUTION_BACKEND_WIRING,
  FAILOVER_ELIGIBLE_FAILURES,
  FAILOVER_REQUIRES_USER_APPROVAL,
  PRODUCTION_BACKEND_FAILOVER_ENABLED,
  approvedFailoverBackends,
  buildBackendStopEvidence,
  classifyBackendFailure,
  evaluateBackendDispatch,
  inspectRoundArtifacts,
  isFailoverEligible,
  routeExecutionRequest,
  type BackendAttempt,
  type BackendDispatchDecision,
  type BackendFailureClass,
  type BackendRouteRecord,
  type BackendStopEvidence,
  type BackendStopReason,
  type ExecutionBackend,
  type ExecutionBackendKind,
  type ExecutionBackendResult,
  type ExecutionRequest,
  type ExecutionRouteOutcome,
  type RoundArtifacts,
} from "./v3/execution-backend.js";
export { createIsolatedWorktree } from "./v3/isolation.js";
export {
  recordUsageLedger,
  summarizeUsageLedger,
  usageLedgerPath,
  type UsageLedgerEntry,
  type UsageLedgerSummary,
} from "./usage-ledger.js";
export {
  runAutonomousObligationLoop,
  type AutonomousEvent,
  type AutonomousObligation,
  type AutonomousState,
  type AutonomousHandlers,
  type AutonomousTelemetry,
} from "./v3/autonomous-loop.js";
export {
  OBLIGATION_STATUSES,
  HUMAN_CATEGORIES,
  summarizeObligations,
  syncObligationsFromProject,
  loadObligationLedger,
  saveObligationLedger,
  loadHumanBacklog,
  addHumanBacklogItem,
  markObligationHumanBlocked,
  resolveHumanBacklogItem,
  obligationsPath,
  humanBacklogPath,
  type Obligation,
  type ObligationStatus,
  type HumanCategory,
  type ObligationLedger,
  type HumanBacklog,
  type HumanBacklogItem,
} from "./v3/obligations.js";
export {
  HUMAN_CATEGORIES as HUMAN_BOUNDARY_CATEGORIES,
  HUMAN_SCOPES,
  isHumanCategory,
  isHumanScope,
  assertHumanCategory,
  isTechnicalHumanReason,
  validateHumanRequiredItem,
  validateHumanResponse,
  compileMinimalHumanRequired,
  filterUnresolvedHumanCandidates,
  evaluateHumanBoundary,
  humanResponseAppliesTo,
  humanRequiredPath,
  humanRequiredMarkdownPath,
  humanResponsesPath,
  persistHumanRequired,
  persistHumanResponse,
  ingestHumanResponse,
  humanResponseAuditValue,
  type HumanCategory as HumanBoundaryCategory,
  type HumanScope,
  type HumanRequiredItem,
  type HumanResponse,
  type HumanCandidate,
  type HumanBoundaryStatus,
  type HumanGateCounts,
} from "./v3/human-boundary.js";
export {
  RECOVERY_OPEN_MARKER,
  RECOVERY_CLOSE_MARKER,
  HUMAN_REASON_CATEGORIES,
  parseChiefRecoveryDecision,
  prepareChiefRecovery,
  applyChiefRecoveryDecision,
  persistWorkerBlock,
  stableFailureSignature,
  normalizeFailureSignature,
  recordFailureSignature,
  type FailureSignatureRecord,
  type RecoveryAction,
  type ChiefRecoveryDecision,
  type RecoveryPreparation,
} from "./v3/recovery.js";
export {
  buildRecentDevlogContext,
  createDevlogHandoff,
  validateSemanticContext,
  validateDevlogHandoff,
  writeDevlogDecision,
  writeDevlogResult,
  type DevlogEntry,
  type DevlogHandoffOptions,
} from "./devlog.js";
export {
  runIntegrationUatPhase,
  type IntegrationUatAction,
  type IntegrationUatOutcome,
  type IntegrationUatResult,
  type V3IntegrationUatConfig,
} from "./v3/integration-uat.js";
export {
  GATE_LEVELS,
  GATE_OUTCOMES,
  RELEASE_READINESS,
  SOURCE_ORIGINS,
  INGESTIBLE_SOURCE_ORIGINS,
  CHECK_SEVERITIES,
  INSPECTION_AUTHORS,
  ISSUE_PRIORITIES,
  P0_CORRUPTION_KINDS,
  GOAL_DRIFT_CHECKS,
  PERIPHERAL_WORK_KINDS,
  V4_SIGNALS,
  P0_OBLIGATION_CHAIN,
  P0_SUPPRESSED_WORK,
  isGateOutcome,
  isSourceOrigin,
  type GateLevel,
  type GateOutcome,
  type ReleaseReadiness,
  type SourceOrigin,
  type SourceProvenance,
  type CheckSeverity,
  type InspectionAuthor,
  type ProductIntegrityCheckResult,
  type ProductEvidence,
  type IssuePriority,
  type P0CorruptionKind,
  type ProductIssue,
  type MachineGateRecord,
  type ProductGateRecord,
  type ReleaseGateRecord,
  type GateRecord,
  type GoalDriftCheck,
  type PeripheralWorkKind,
  type ProductAnchor,
  type V4Signal,
  type P0Obligation,
  type P0SuppressedWork,
  type RunJournalEntry,
} from "./v4/domain.js";
export {
  PRODUCT_ANCHOR_NOT_RUN_THRESHOLD,
  auditUserValueDelta,
  buildRunJournalEntry,
  deriveP0Reprioritisation,
  deriveProductGateRecord,
  deriveReleaseReadiness,
  evaluateGoalDrift,
  evaluateProductAnchorRequirement,
  evaluateSourceProvenance,
  isP0Issue,
  p0CorruptionKinds,
  p0Issues,
  renderRunJournal,
  sortIssuesByPriority,
  type ReleaseReadinessVerdict,
  type ProductAnchorRequirement,
  type GoalDriftInput,
  type UserValueDeltaAudit,
  type ProvenanceVerdict,
  type P0Reprioritisation,
  type BuildJournalInput,
} from "./v4/policy.js";
export {
  P0_OBLIGATION_PRIORITY,
  P0_DEMOTED_PRIORITY_CAP,
  evaluateV4Round,
  isWorkAllowed,
  p0ChainObligations,
  reprioritiseObligationsForP0,
  type V4RoundInput,
  type V4RoundDecision,
} from "./v4/supervisor.js";
export {
  V4_CHIEF_VERDICTS,
  V4_CHIEF_DIMENSIONS,
  parseV4ChiefDecision,
  renderV4ChiefEvidence,
  evaluateV4ChiefOutcome,
  type V4ChiefVerdict,
  type V4ChiefDimension,
  type V4ChiefJudgement,
  type V4ChiefDecision,
  type V4ChiefEvidence,
  type V4ChiefOutcome,
} from "./v4/chief.js";
export {
  RUN_MODES,
  DEFAULT_RUN_MODE,
  RUN_MODE_ENV_VAR,
  isRunMode,
  parseRunMode,
  resolveRunMode,
  resolveV4Capabilities,
  describeV4Capabilities,
  type RunMode,
  type ResolveRunModeInput,
  type V4Capabilities,
} from "./v4/run-mode.js";
export {
  V4_ANCHOR_VERSION,
  V4_ANCHORS_FILENAME,
  MalformedAnchorRecordError,
  anchorsPath,
  emptyAnchorRecord,
  loadAnchorRecord,
  saveAnchorRecord,
  appendAnchor,
  recordAnchor,
  type ProductAnchorRecord,
} from "./v4/anchor-store.js";
export {
  V4_JOURNAL_FILENAME,
  appendJournalEntry,
  journalPath,
  readJournal,
  recordJournalEntry,
} from "./v4/journal.js";
export {
  evaluateV4Preflight,
  v4PreflightError,
  type V4PreflightInput,
  type V4PreflightResult,
} from "./v4/preflight.js";
export {
  DEFAULT_PRODUCT_GATE_TIMEOUT_MS,
  parseProductGatePayload,
  runProductGateCommand,
  type ProductGatePayload,
  type ProductGateRunResult,
} from "./v4/product-gate.js";
export {
  DEFAULT_V4_RUN_ID,
  productGateCommandFromEnv,
  resolveV4RunId,
  runV4Round,
  type V4RuntimeOptions,
  type V4RoundRequest,
  type V4RoundOutcome,
} from "./v4/runtime.js";
